### ISSUE TITLE
Unable to start proxy because of missing 'OPTIONAL_ARGS'

### ISSUE THREAD

**Issue by lamehost** [napalm-automation/napalm-salt#19]
I have found a small issue in salt/proxy/napalm.py .
The proxy process fails to start without this patch

[napalm.txt](https://github.com/napalm-automation/napalm-salt/files/664016/napalm.txt)

**Comment by mirceaulinic** [comment]
Thanks for reporting this @lamehost!
I've also noticed that: they should be fixed in the next public release of Salt (2016.11.2). I will leave this open till then.

**Comment by mirceaulinic** [comment]
I've just noticed the title tho... Can you please provide more details @lamehost? The execution of arbitrary calls should not influence at all the start of the proxy process.
In worst case, the error would be whilst collecting grains which means an error in the ```get_facts``` of the corresponding driver and we'll need to address this.

Would you mind providing the following:

- driver name
- relevant logs from ```/var/log/salt/proxy``` and ```/var/log/salt/master``` (just the chunks containing the error messages)
- ```salt --versions-report```

Thanks!

**Comment by lamehost** [comment]
[proxy_log.txt](https://github.com/napalm-automation/napalm-salt/files/670998/proxy_log.txt)
@mirceaulinic please look at the attachment.

This is the content of the pillar:
```
root@5ea276ee6c97:/# cat /srv/pillar/192_168_0_1.sls 
proxy:
  driver: ios
  host: 192.168.0.1
  passwd: .b4Ld0ns
  proxytype: napalm
  username: marco
```


And here's the version of SaltStack i am running:
```
root@5ea276ee6c97:/# salt --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 8.1.3
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13rc1 (default, Dec  4 2016, 14:12:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 4.8.0-2-amd64
         system: Linux
        version: debian stretch/sid 
```

As you can see on the log the proxy trhows errors right after it boots

**Comment by mirceaulinic** [comment]
Hi @lamehost,

Thanks for details! No, that's nothing to worry about - the error messages are raised when collecting the grains before the connection is established. They are collected successfully later,  after init.
The message right before reflects that: "The following CRITICAL message may not be an error; the proxy may not be completely established yet.".
At the bottom at the file I see the following two lines:

[INFO    ] Connected (version 2.0, client Cisco-1.25)
[INFO    ] Authentication (password) successful!

Which say that the connection succeeded. Did you have any issues running the minion?

**Comment by mirceaulinic** [comment]
This was solved in https://github.com/saltstack/salt/pull/38374.
`2016.11.2` is already tagged and packed and will include this fix.
However, as previously said, this does not block the startup of the minion.

@lamehost do you still see the same issue? I think you may need to check if the minion key has been accepted by the master. To do so, execute: `salt-key -L` to see the unaccepted keys and `salt-key -a <minion ID>` to accept the authentication.

Thanks for reporting this!

**Comment by lamehost** [comment]
@mirceaulinic ,

I am sorry, i have overlooked your previous email
Everything works as expected now.

And yes, you were right the script didn;t crash.
Sorry for the mistake.

Regards

**Comment by mirceaulinic** [comment]
No problem at all - glad it works!
It's very good you have pointed out that error. Although it didn't break anything, it didn't look comfortable either in the logs. So thanks to your reminder, I have gate it in 2016.11.2.

Cheers,
Mircea
