### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by compyy** [napalm-automation/napalm-salt#29]
Hi,

Please update few things in docs:
In /etc/salt/pillar/ save a file called top.sls >> it should be /srv/pillar/

also:
/etc/systemd/system/salt-proxy@.service >> /etc/systemd/system/salt-proxy.service

Regards,

**Comment by mirceaulinic** [comment]
Hi @compyy:

> In /etc/salt/pillar/ save a file called top.sls >> it should be /srv/pillar/

The pillars directory can be wherever you want. `pillar_roots` specifies to the master where it should look for: https://github.com/napalm-automation/napalm-salt/blob/master/master#L321-L323
The default location depends also on the platform. On windows, for example, for sure it will not be under `/etc/salt/pillar` or `/srv/pillar`.

> /etc/systemd/system/salt-proxy@.service >> /etc/systemd/system/salt-proxy.service

Again, this can be anything you want. Additionally, using the `@` you can control the process per device, e.g.: `systemctl start salt-proxy@deviceX` and will start the process for `deviceX` without affecting the others.
In your environment, you can call that file what you feel comfortable with: `/etc/systemd/system/my-custom-irrelevant-name.service` is equally valid.

If you notice anything that does not look sane, you are always welcome to submit a PR. If your changes are valid, they will get merged.
Let me know if you have any other concerns.

Mircea

**Comment by compyy** [comment]
Hello,
I agree but by default it goes into srv/pillar whereas in doc it says /etc/salt/pillar and it generates following error, which has no reference how to fix it, even if you google it.

No proxy key found in pillar or opts for id R1. Check your pillar/opts configuration and contents.  Salt-proxy aborted.

for Service part, i understand the concept of @ now, thanks.

**Comment by mirceaulinic** [comment]
I know @compyy.
Did you see https://www.nanog.org/sites/default/files/1_Ulinic_Network_Automation_At_v1.pdf? (Slides 21 & 23 in particular).
`pillar_roots` and `file_roots` are two of the most important options to be careful of in the master config. There are many other that may help you, see https://docs.saltstack.com/en/latest/ref/configuration/master.html
I emphasised how those two interact with the rest of the features. If they are not configured correctly, it is not going to work.
Hope that helps.

**Comment by compyy** [comment]
Ok thanks.
