### ISSUE TITLE
Update Doc

### ISSUE THREAD

**Issue by ipv6freely** [napalm-automation/napalm-salt#42]
Found that using apt-get to install salt was giving me v2015. Might want to just add a note pointing out that you should make sure you are using Nitrogen (by following this guide for example), or something similar.

**Comment by mirceaulinic** [comment]
Thanks for pointing this out @ipv6freely - would you be happy to solve this issue and improve the docs?

**Comment by ipv6freely** [comment]
Yeah I can do that. Let me work through until I get a working installation and then I'll do it.

**Comment by mirceaulinic** [comment]
@ipv6freely checking in here - what's the status?
