### ISSUE TITLE
One salt-proxy for each host?

### ISSUE THREAD

**Issue by kheide** [napalm-automation/napalm-salt#51]
Have I understood it correctly that you’ll have one salt-proxy running for each device you want to utilize napalm against? That seems a bit rough say in a network of 2-3000 devices managed.

**Comment by mirceaulinic** [comment]
Hi @kheide. Your understanding is correct: you need as many Proxy Minion as devices to manage. I assume you not are planning to manage these processes manually (the same goes with any process, whatever its nature would be)... in that case, managing 1 process or thousands becomes equally simple, as I tried to explain in https://mirceaulinic.net/2018-09-27-network-automation-at-scale/. Please let me know if you have any questions!

Additionally, I'm also working on an alternative "proxyless" implementation (almost ready, will write up about it soon-ish) which only requires you to have just one single process, the Salt Master and nothing else. Hope this helps! :-)

**Comment by kheide** [comment]
Thanks for the reply. I'm not concerned about the managability for the proxies, but rahter the resources it would consume and the risk of something going wrong. 

Do you have a timeframe on the proxyless implementation? Or have it in a branch somewhere?
