### ISSUE TITLE
Current solution is not scalable

### ISSUE THREAD

**Issue by thugcee** [napalm-automation/napalm-salt#63]
After few weeks of working on my server ```python3 /usr/bin/salt-proxy``` for ssh session takes 28.145 MB + 215.43 MB of VmRSS, so for not so big network of 400 devices it would need 97 GB of RAM just for a bunch of mostly idle processes. 

Is there any chance to handle all devices by one proxy [in future versions]?

Salt version: 2019.2

**Comment by barneysowood** [comment]
You lose some on the benefits of always on proxies, but depending on your use case, salt-sproxy (https://mirceaulinic.net/2019-06-17-minionless-salt-automation/) might help. Or possibly https://github.com/gtmanfred/salt-proxies - although that hasn't had much development as far as I can see.

**Comment by thugcee** [comment]
@barneysowood, `salt-sproxy` is great! After having done configuration for proxy-minions I just had to pip install its package and voilà: everything works! Thank you for pointing me to the exhaustive tutorial.
