### ISSUE TITLE
Issue with installing napalm

### ISSUE THREAD

**Issue by StewAlexander-com** [napalm-automation/napalm-salt#70]
Failed install with this information, can you point us to a fix, or is this a bug?

```support@saltmaster2:~$ salt --version```
**salt 2017.7.4 (Nitrogen)**
```support@saltmaster2:~$ python3 --version```
**Python** 3.6.9**
**pip 21.3.1**

-------

```
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ac/ca/48957f603be2cd011455ce9644231a1e9319f0d6409dcd051a7b62cf0d21/napalm-junos-0.11.0.tar.gz#sha256=5078cfbcad742c5a241e2a62242d5ffca3e34dd35d180e948f68a67979e1ecd1 (from https://pypi.org/simple/napalm-junos/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached napalm-junos-0.10.3.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dp_nxlk5/napalm-junos_e290c4650c884b3eb6883343077cce74/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dp_nxlk5/napalm-junos_e290c4650c884b3eb6883343077cce74/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1aidhryi
       cwd: /tmp/pip-install-dp_nxlk5/napalm-junos_e290c4650c884b3eb6883343077cce74/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-dp_nxlk5/napalm-junos_e290c4650c884b3eb6883343077cce74/setup.py", line 6, in <module>
      from pip.req import parse_requirements
  ModuleNotFoundError: No module named 'pip.req'
  ----------------------------------------
''

**Comment by ktbyers** [comment]
@StewAlexander-com This looks like a very old version of NAPALM

napalm-junos 0.11.0 (2017)

napalm-junos itself was deprecated in ~2017.

You should be using the main NAPALM repository.

**Comment by StewAlexander-com** [comment]
@ktbyers - Where is this NAPALM repo, we used the instructions we say on this readme .... maybe it has something to do with our old version of Salt?

**Comment by ktbyers** [comment]
Yeah, I suspect it is due to the really old version of Salt. There is probably a way to install the really old version of things to make it work. That specific error is due to a `pip` change made a long time ago...so if you go to a really old version of `pip` you can probably install things.

I am not a salt person; I work on the NAPALM project though. So I would typically install NAPALM just using.

```
pip install napalm
```

But that also implies at least needing to change your import statements as you were previously using `napalm-junos` which we deprecated in ~2017.

**Comment by StewAlexander-com** [comment]
We went down a different much easier path

FYI ```salt-cp``` is a pretty cool salt function that will copy a file from the salt master to a minion ... which allowed us to copy over SNMP files to get all of our Linux servers up on SNMP
